#!/usr/bin/env bash

#/ command: semver:promote-to-release: "promote special version to release"
#/ usage: rerun semver:promote-to-release  --input_version <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INPUT_VERSION

. $RERUN_MODULE_DIR/lib/functions.sh promote-to-release || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
semver_promote_to_release "$INPUT_VERSION"
# - - -

# Done. Exit with last command exit status.
exit $?
