#!/usr/bin/env bash

#/ command: semver:bump: "bump semantic version segment"
#/ usage: rerun semver:bump  --input_version <>  --segment <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INPUT_VERSION SEGMENT

. $RERUN_MODULE_DIR/lib/functions.sh bump || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

