# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Oct 11 11:41:50 CDT 2017
#
#/ usage: semver:extract  --input_string <> [ --trim_suffix <>] 

# _rerun_options_extract_ - Parse the command arguments and set option variables.
#
#     rerun_options_extract "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
  
    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --input_string) rerun_option_check $# $1; INPUT_STRING=$2 ; shift 2 ;;
            --trim_suffix) rerun_option_check $# $1; TRIM_SUFFIX=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$INPUT_STRING" ]] && { echo >&2 "missing required option: --input_string" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${INPUT_STRING:=}
: ${TRIM_SUFFIX:=}
# Default command line to null if not set
: ${_CMD_LINE:=}
